create table if not exists public.analysis_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  image_path text,
  mode text not null check (mode in ('single', 'battle')),
  result jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists analysis_history_user_id_created_at_idx
  on public.analysis_history (user_id, created_at desc);

alter table public.analysis_history enable row level security;
